apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: oxifed-dev

patches:
- target:
    kind: ClusterRoleBinding
    name: oxifed-operator-binding
  patch: |-
    - op: add
      path: /subjects/0/namespace
      value: oxifed-dev
